export const androidTopApps = [
  {
    app_id: "com.google.android.apps.subscriptions.red",
    app_name: "Google One",
    app_category: "Productivity",
    app_developer: "Google LLC",
    num_downloads: "500,000,000+",
    app_description:
      "The Google One app lets you automatically back up your phone and manage your Google cloud storage.\n• Automatically back up the important things on your phone, like photos, contacts and messages using your free 15 GB of storage that comes with every Google account. If you break, lose or upgrade your phone, you can restore everything to your new Android device.\n• Manage your existing Google account storage across Google Drive, Gmail and Google Photos.\n\nUpgrade to a Google One membership to get even more: \n• Get as much storage as you need for your important memories, projects and digital files. Choose the plan that works best for you. \n• Get extra protection for your phone with a VPN that encrypts your online activity and helps keep your personal information safe\n• Get exclusive access to Google experts for help with all of Google’s products and services. If you have a question or need assistance, our team of Google experts is just a tap away.\n• Share your storage with up to 5 additional people. This gives each person access to more storage from your plan, but not access to each other’s files.",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.google.android.apps.subscriptions.red",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 4,
    photos: [
      "https://play-lh.googleusercontent.com/Hq1_md0WKFpe6InQDSxckKJRs8SgVFQVWxxl3i-ajrzXKa1fFSp1oJPuKODDFRNFyc4A",
      "https://play-lh.googleusercontent.com/Pz5zeJ7qzbfs0LmGQI-8dH957NuB49WeSxrbNEhzxs0pD2_4BTRinyT5M_UULQH2xA",
      "https://play-lh.googleusercontent.com/yAN2k-Xwt_0omZGVuBAfU2Kn-v5GBDLTineLs1lbH2X6IlWPsHxMsTLfPBPvmt3y9qg",
      "https://play-lh.googleusercontent.com/DEoNef6aL5xnBkgd8lXL9MiSA2BCa5aFDqq5t2hmUvMVhTdZoVQWUVud4H8RKFoFow",
      "https://play-lh.googleusercontent.com/WA26z-ix6Z3Ep1mIsjVmO2HGH07yhJ0s_sdDqUFMqQLdKSPmrUBYymrf1i4kM0GM-SE",
      "https://play-lh.googleusercontent.com/TesXWUcblbj1Ep_mFv6s4yOKLLra9L6VgI0GOZ9xttxM43Al5a7uPTw9DqOBSvHVZ11z",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/DGAleS46qOedNzJGsB3e29QLpL6Qi6EwIDze95nBvxMAMGEmbE6KOW__2haEkHVDs4Y",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:4Ltr3pqgCSQ",
  },
  {
    app_id: "com.hbo.hbonow",
    app_name: "HBO Max: Stream TV & Movies",
    app_category: "Entertainment",
    app_developer: "WarnerMedia Global Digital Services, LLC",
    num_downloads: "100,000,000+",
    app_description:
      "Limited-time offer. Save over 40% when you prepay for a year. Savings based on yearly plan paid upfront vs. monthly plan paid over 12 mos. Ends 10/30/22. See HBOMax.com.\n\nHBO Max is a premium streaming app that combines all of HBO with even more must-see TV shows, blockbuster movies, and exclusive Max Originals. It’s everything you love, all in one place. All of HBO. All of the greatest TV and hit movies. All yours. Available anytime to stream on your favorite screens. \n\nWith unlimited access to thousands of hours of entertainment, we’ve got something for everyone in your family. Keep up with fresh episodes from the latest HBO shows and fall back in love with the iconic TV everyone’s still talking about. Watch new movies from D.C. and Warner Bros, plus the comedies, dramas, and classics you love. \n\nSo kick back in your comfiest loungewear and find your next favorite from one of our curated hubs, including HBO, D.C., the Cartoon Network Collection, Classics curated by TCM, Sesame Workshop, and more. With HBO Max, you’ll always find something new to stream. \n\n\nHere’s what’s waiting for you:\n\n• All of HBO with even more critically-acclaimed movies, binge-worthy TV shows, and Max Originals.\n• Bingeable collections hand-picked by our editorial experts—not robots.\n• One-of-a-kind kids experience with flexible parental controls.\n• HBO Max Hubs devoted to beloved brands including HBO, the Adult Swim Collection, the Cartoon Network Collection, Looney Tunes, Classics curated by TCM, DC, and more.\n• Download episodes and movies to your phone or tablet to watch offline, anytime.\n• Up to five viewer profiles with customizable profile images.\n\n\n\nContent and feature availability on HBO Max may vary by region. Some titles and features shown above may not be available in your country.\n\nHBO Max is only accessible in certain territories.\n\nFor help, please visit help.HBOMax.com.\n\nPrivacy Policy: https://www.hbomax.com/privacy\nTerms of Use: https://www.hbomax.com/terms-of-use\nFor California residents only, manage sharing your data at: http://warnermediaprivacy.com/do-not-sell",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.hbo.hbonow",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 3,
    photos: [
      "https://play-lh.googleusercontent.com/buGpC6LJ0jwYJqpK4ytBl2Yvv8nql7dZ2FFiqUSbmJiGSL_qdVl7SHD25m4hWFBT_j-4",
      "https://play-lh.googleusercontent.com/XFndIHkTWOGbfVMOpPPdZxZJ_nTgyI6wrF47LoTSU8IfpVv9lsna8Nig1CiMk394WQ",
      "https://play-lh.googleusercontent.com/9Ox8AdPQp2iXMoW1H0wvKGA5MfKVbNB_2nPTXkkH-jp3HhMAiZCd38YxXqmhAVmpom9Y",
      "https://play-lh.googleusercontent.com/HWzli0YE3ltQRxGsfcnzpILWHcQI_cZri9-HLtzKMLJgR2u844Q7CdnS7qdudQN1Hek",
      "https://play-lh.googleusercontent.com/wwJM9J65L4k5IWc0kxvMRKn-VdhNW4716hLRa9NUTXXmJRTkIy0WkSWrT4Aliz72tsiD",
      "https://play-lh.googleusercontent.com/5fVeU2bX9yiUDCGAVRvTi3KgZUVcP73lPkSttGATNBry05ioX7pVmK9KYX5LieloETg",
      "https://play-lh.googleusercontent.com/jPIgVZ3Hbm88FlYAe1uGtG2BclfXiV4vy-UhpjTX4zXoqQO_14Etwhd0VfTpJYDYhI8",
      "https://play-lh.googleusercontent.com/BrehyVgiz2sXIJ_qPoN3kTJzHPHVuwB0MnbxAzJzNvA6DP9DdVVbxWJNoO9gbAGZRuI",
      "https://play-lh.googleusercontent.com/t7GF74OxZjT4BXFIMoUoOUTxIwn8xObZL-AQm0liGZSXPsEGON3usplnjooixN5gOQ0",
      "https://play-lh.googleusercontent.com/xyPDkNLGK42qZDNMb3GmnTZQd0-D4LKshtpyKUZ5cDhZ5xxZqDwUlWoY6pvtx8Yo_NM",
      "https://play-lh.googleusercontent.com/NxprhFLX2ht_-c2DucecCmWGlcfzbY_WI7foL-zjVhBs1d_mbhy-B-Kwq4GOR0VbZOc",
      "https://play-lh.googleusercontent.com/2DxZ7Jo-9HJBALV0Rg5jnZy8yV7n1RXmJYqswwAlPvDH6n-SQ8GYLfPfz58ihq8JHWc",
      "https://play-lh.googleusercontent.com/a-Ma7uIIKx0j55EzYbKYHJAEh2VLZrWV_kIoJHu_LM9mlTq0O8y44DqjloPwrLmNocjy",
      "https://play-lh.googleusercontent.com/DzHJXYz8_zvF7DSk4nPRZ53jACf1JcblWLZd2ghd-jlzqpDH9jbtKCxJQzlKGhkK82Q",
      "https://play-lh.googleusercontent.com/dercTneZwcgNXrFJNtc4Bj8jd9_uc-B3OGQVDpgOtDNdh9qya0E0LEE0mOwPclG2AQ",
      "https://play-lh.googleusercontent.com/UEs1N9UUTx0oyoeV-9dom7ZN505d-j0M22s3g9XOBFU68HVDofymDNMIfonGN9ylWg",
      "https://play-lh.googleusercontent.com/QJws4Z3lUdJwcxUMB_otKtjHZpsLKzfgGggPuhD4LmGBvxOUY0lrFkznJ9VTD0VaBkq8",
      "https://play-lh.googleusercontent.com/W9HbcDkxt_2wAAvJIJZP2Ip-kDYv7TU7xAq5pE1cM8SjIdcTIxgwnazYAwvYkLfoSQ",
      "https://play-lh.googleusercontent.com/pPxHxScTMZIiv809HC_sDALYZKtKLEyAx70XZcjhB_qi03XyAwkVbdAuteYJzZGOg6c",
      "https://play-lh.googleusercontent.com/_umbX0VeQp51568QpOnPOyl2up_g7MNJR6L9gwDvfQ2CSBfyEWvKDKzOuchaesHdm6Pe",
      "https://play-lh.googleusercontent.com/Pa_WDBiQo87cWX9q2AE09HNe2Du1NSL0OXT_63kO14MVvxTVvrggHWKI-utGBgdDYg",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/1iyX7VdQ7MlM7iotI9XDtTwgiVmqFGzqwz10L67XVoyiTmJVoHX87QtqvcXgUnb0AC8",
    trailer: null,
  },
  {
    app_id: "com.zhiliaoapp.musically",
    app_name: "TikTok",
    app_category: "Social",
    app_developer: "TikTok Pte. Ltd.",
    num_downloads: "1,000,000,000+",
    app_description:
      "TikTok is THE destination for mobile videos. On TikTok, short-form videos are exciting, spontaneous, and genuine. Whether you’re a sports fanatic, a pet enthusiast, or just looking for a laugh, there’s something for everyone on TikTok. All you have to do is watch, engage with what you like, skip what you don’t, and you’ll find an endless stream of short videos that feel personalized just for you. From your morning coffee to your afternoon errands, TikTok has the videos that are guaranteed to make your day.\n\nWe make it easy for you to discover and create your own original videos by providing easy-to-use tools to view and capture your daily moments. Take your videos to the next level with special effects, filters, music, and more. \n\n■ Watch endless amount of videos customized specifically for you\nA personalized video feed based on what you watch, like, and share. TikTok offers you real, interesting, and fun videos that will make your day.\n \n■ Explore videos, just one scroll away\nWatch all types of videos, from Comedy, Gaming, DIY, Food, Sports, Memes, and Pets, to Oddly Satisfying, ASMR, and everything in between.\n \n■ Pause recording multiple times in one video\nPause and resume your video with just a tap. Shoot as many times as you need.\n \n■ Be entertained and inspired by a global community of creators\nMillions of creators are on TikTok showcasing their incredible skills and everyday life. Let yourself be inspired.\n\n■ Add your favorite music or sound to your videos for free\nEasily edit your videos with millions of free music clips and sounds. We curate music and sound playlists for you with the hottest tracks in every genre, including Hip Hop, Edm, Pop, Rock, Rap, and Country, and the most viral original sounds.\n\n■ Express yourself with creative effects\nUnlock tons of filters, effects, and AR objects to take your videos to the next level.\n\n■ Edit your own videos \nOur integrated editing tools allow you to easily trim, cut, merge and duplicate video clips without leaving the app.\n\n* Any feedback? Contact us at https://www.tiktok.com/legal/report/feedback or tweet us @tiktok_us",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 4,
    photos: [
      "https://play-lh.googleusercontent.com/qQhwrVXDA7HMyNrK5Gl91GiBATRcwY3hfuNIYjlVJpo5LE8aouvlmQohaaPNo_Y5gA",
      "https://play-lh.googleusercontent.com/0Quk7ItYKo75MuIHggXd2OsIU87647sUWJFlzEKzLdT0c29Em0ahUEwB1CMuLXk_BbA",
      "https://play-lh.googleusercontent.com/L1lGajSNsrp6eom7k7ThNn4c49vcqB3ak3ume0uxfDX9siN1fGNJTmXpfkDJO14t3j4h",
      "https://play-lh.googleusercontent.com/WBK3o6EPBGwX6auA0dFEmbPoQ_OALgzDAs5AyjzZIZwC5AXPrQthr8uL3rwgom3DhWE",
      "https://play-lh.googleusercontent.com/065CXfgBlqMOHZdm1U2uNP6TYbK7E6F2EVIg-pRcU-oYLUQbI69Zdz_13ZTP_NGyxw",
      "https://play-lh.googleusercontent.com/plyGX_oOTlg3MePYVHEu3FUf1QwiMXQdBDexxjLhI9In6hl4Lg1j7Bft6t_FWAfVrUw",
      "https://play-lh.googleusercontent.com/GghmJNEZwdkGxHffx6P9e3L2Nzvm__CfIp6Mw7VDLL4VWDARE51YgQKvtTCVW0il0_8",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/z5nin1RdQ4UZhv6fa1FNG7VE33imGqPgC4kKZIUjgf_up7E-Pj3AaojlMPwNNXaeGA",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:-d261W5Vb40",
  },
  {
    app_id: "com.disney.disneyplus",
    app_name: "Disney+",
    app_category: "Entertainment",
    app_developer: "Disney",
    num_downloads: "100,000,000+",
    app_description:
      "Disney+ is the streaming home of your favorite stories. With unlimited entertainment from Disney, Pixar, Marvel, Star Wars and National Geographic, there's always something to explore. Watch the latest releases, Original series and movies, classic films, and TV shows with new stories added every week. \n\nWhen opening Disney+ for the first time on or after March 16, all subscribers in the U.S. will be prompted to update their Parental Controls. This includes the option to select content ratings restrictions for each profile as well as to add a PIN to lock profiles. Those that choose to keep their settings the same will continue to enjoy Disney+ as they always have within a TV-14 content rating environment, with the option to make changes at any time under Profile settings.\n\nStream and download Originals like Loki, and fan favorites like Frozen and The Simpsons.\n\nWith Disney+, you get:\n• Exclusive new Originals from the creators of Disney, Pixar, Marvel, Star Wars, and National Geographic\n• Access to new releases, timeless classics and past seasons of your favorite TV shows\n• GroupWatch, a way to watch Disney+ together, even when you’re apart\n• Unlimited downloads on up to 10 devices\n• Over 100 titles in 4K UHD and HDR\n• The capacity to watch on four screens at once at no extra cost\n• IMAX Enhanced, see the full scale and scope with IMAX's expanded aspect ratio. Available with certain Marvel titles and accessible on all devices where Disney+ is supported. \n• Multiple parental control features including Profile PIN, Kids Profiles, Kid-Proof Exit. Account holders can change an individual profile’s content rating at any time under Profile settings. \n\nFor help with Disney+, please visit: http://help.disneyplus.com.\nFor our Subscriber Agreement and other policies please visit: https://disneyplus.com/legal.\n\nYour California Privacy Rights: https://www.disneyplus.com/legal/your-california-privacy-rights\nDo Not Sell My Information: https://www.disneyplus.com/legal/privacy-policy \n\nThe content available on Disney+ may vary by region. Some titles shown above may not be available in your country.",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.disney.disneyplus",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 4,
    photos: [
      "https://play-lh.googleusercontent.com/_4R1YWIIuj_OmpD6JYtfNxlawwXLJbeZVd0G_5Cb-2aW3tecPjx9LhT0ZJI2liJojqE",
      "https://play-lh.googleusercontent.com/mXv7_OKNj6ePbj_92a9xUUCeg9nK3bYhN_Hw_Jy6Md5S_2LQhqR8G8HRUSIfqcxYAQ",
      "https://play-lh.googleusercontent.com/19AlS6zizb4AjpHwOxGYriRoHlS6rY59qxZOIZLYAWK-T1NaZDUnXDERRmyU0M6RZ5s",
      "https://play-lh.googleusercontent.com/IG-AhQth21-3BHs49ZwX0iviAcZs8XqgkD1dOaQnV35DeOqaHlLldtd1ToR_r4kBdXH_",
      "https://play-lh.googleusercontent.com/F5nnPLV25LiHMRWMb_WkDR9BZGl9sgMw5gRdEYkn-8Hqs4lGxAowCxp9MhsopMWpVg",
      "https://play-lh.googleusercontent.com/7N5dIBRR98_bVPnnX-HK236Rqr8kEcU3ZfNGGpgKh-3s1MtligTzC8DHgxZ3BbBkFA8",
      "https://play-lh.googleusercontent.com/UcHYWciu6IlQPniHtZzg51M994HzyKJXmvur1j8n4slXZQO_lqoo_WRQ1pJQCGBuGA",
      "https://play-lh.googleusercontent.com/sY9EpQdOQ5QM458oDruw3-IT0FQBnY8rykdHaCrD5swerCet_1ZaEriePsAL5O5VH1w",
      "https://play-lh.googleusercontent.com/m4yjWlcV0XzIok-hnAMu-F8i0hAmFsViUJvkMT221FlJaLO6CQHnguDW2qDUkNvPiw",
      "https://play-lh.googleusercontent.com/USwrGZQbKCNddkrT6fPXwSBz69yM5PV2afCvgPnXT4y5Zv4ddBLuk2HFWxHWZcppGEU",
      "https://play-lh.googleusercontent.com/nIu9Nb84PAJR4Gvfx5p-D2U6xGhgNjtomQJYOhkbp1h3bqTzEeWWslJZCwHyxAHqXlM",
      "https://play-lh.googleusercontent.com/tujvNKn5mhn5b8J4XntpnlGfmcmx_yZ3GOX8xN0uz5Q-G7PKd8MALTedBmty3cplN8Fr",
      "https://play-lh.googleusercontent.com/Uwb2Dtkr2S9nv6qbq6MJxw79-84CN3VmtG44hCZ6Wqti8U3gU8VLe4cgiE98vbIk2oE",
      "https://play-lh.googleusercontent.com/mlnN0tbBK5xb51MkXjrLMmfrQqVzNIK-glR07rNqJB7gDfK6Ggg8fFI6jgmAU5hqKw",
      "https://play-lh.googleusercontent.com/9A1kHICb9aXEN2A9CW7-Bcym_yvDD3YdMtf9mQ6FI3jLado5MzizpKrDmIDatE7MNZYq",
      "https://play-lh.googleusercontent.com/lXPIQJQu3ENNfFwBkPZtwSScHpHZsBjc6zGCbLOhCdOAi1lEVCobDfB5c5vH0KKBvVqz",
      "https://play-lh.googleusercontent.com/EJIPIIRXEwb3eZc04YnSFYY3KYUPdy_g6WntJVmWHSOyylXHtzH39G5orgBNp4NTs8SD",
      "https://play-lh.googleusercontent.com/6m_mIWaphJDzctSi2M6KKxQVbvzr5SMRf4uW5xDEpOJ324_3qFnsSJHOyXXYHhQWwZE",
      "https://play-lh.googleusercontent.com/l_LdgneKDgGvJG7PGd6aosT28CBisu2ppSS5JaQz5YhVEzNibwyfE4vinyptb8auwQ",
      "https://play-lh.googleusercontent.com/J13HveJxaN0Ka52FRZbYJr_ttU-aGmZS5G3FMg0YdzxG1uJo2xLvhlJY368jgQv3UWtp",
      "https://play-lh.googleusercontent.com/9YpSz7W_v3XkVF0-vrpsZDEoTWkhb0uzclkyg1tibSLQgCbslmuX4aRcAbMDtXUSgA",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/xoGGYH2LgLibLDBoxMg-ZE16b-RNfITw_OgXBWRAPin2FZY4FGB9QKBYApR-0rSCkQ",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:QX3QPNKV9WY",
  },
  {
    app_id: "com.pandora.android",
    app_name: "Pandora - Music & Podcasts",
    app_category: "Music & Audio",
    app_developer: "Pandora",
    num_downloads: "100,000,000+",
    app_description:
      "Pandora gives you a personalized listening experience that continually evolves with your tastes. \n\nCreate stations from your favorite songs, artists or genres, search or browse to find recommended stations for your mood or activity, and discover podcasts that speak to you. Download today and get instant access to your favorite artists and podcasts, while staying up to date on the most recent singles and releases. From rap and pop to rock and country, play your favorite artists and stay up to date on today’s top hits and releases. Start streaming all of the current global hits and enjoy your own personalized music experience. \n\nTake Pandora with you wherever you go with Android Auto for your daily commute or your next road trip. Enjoy your own personalized music or podcast experience from anywhere on the world’s most powerful music discovery platform. The new voice mode lets you search, play, pause, skip adjust volume & thumb up music with a simple voice command. Start streaming your favorite artist, song, genre, or podcast instantly today for free in your car.\n\nEnjoy everything Pandora has to offer right from the convenience of your wrist, with Google’s Wear OS. With a quick tap, you can control media playback such as play/pause, replay, skip, thumbs, and more. No phone necessary.\n\nWith Podcasts on Pandora, find your favorites and listen to personalized recommendations that actually make sense. Just search on your mobile phone or tablet and play to start listening, then tap + to add to your collection. Find something new by simply browse and tap recommended podcasts to find over 1,400 podcasts, including SiriusXM shows, on-demand whether you're on Pandora Premium, Plus or Radio.\n\nLooking for more?\n\nMeet Pandora Modes - The new way to customize your station experience. Choose from six different modes to switch up the kind of music you're hearing:\n•My Station: The station experience you know and love.\n•Crowd Faves: Hear the most 👍songs by other listeners.\n•Deep Cuts: Hear less familiar songs from station artists.\n•Discovery: Hear more artists who don't usually play on this station.\n•Newly Released: Hear the newest releases from station artists.\n•Artist Only: Hear songs from the station artist.\n\nPandora Premium™\nSubscribe to enjoy personalized on-demand music and podcasts\n\n• Search and play your favorite songs, podcasts, albums and playlists on-demand\n• Create playlists, not worklists – on your own or powered by Pandora\n• Download the music you want for offline listening\n• Unlimited skips and replays\n• Higher quality audio\n• Listen with ad-free music\n\nPandora Plus™\nSubscribe to enjoy personalized radio with ad-free music\n\n• Unlimited personalized stations and podcasts\n• Up to four stations for offline listening\n• Unlimited skips and replays\n• Higher quality audio\n• Listen with ad-free music\n\nPandora Plus subscriptions are $4.99 per month. Pandora Premium subscriptions are $9.99 per month. You’ll be charged as a recurring transaction through your Google Play account. Pending trial eligibility, charges for Plus >($4.99/month) or Premium ($9.99/month) begin at the end of a free trial unless you cancel 24 hours prior to the end of the current subscription month. Any unused portion of a free Pandora Plus trial period will be forfeited if you upgrade to Pandora Premium. You can manage your subscription, cancel or turn off auto-renewal through Account Settings in your Google Play account. Pandora is available to US customers only.\n\nSome advertising exclusions apply. Skips, replays and offline features may be limited by certain licensing restrictions. Pandora may use large amounts of data, and carrier data charges may apply. For best results, we recommend you connect your device to trusted Wi-Fi networks when available.\n\nTerms and conditions:\nwww.pandora.com/legal\nwww.pandora.com/legal/subscription\nwww.pandora.com/privacy",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.pandora.android",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 4,
    photos: [
      "https://play-lh.googleusercontent.com/DGmLad-us9MRt0teOwu3BnXEQvwgoqD_rfVPpmYKxlpVIz-rnFtSUJtm1Dq1qZk4B34",
      "https://play-lh.googleusercontent.com/Gv9YA2qfdxUSZu_BVDDNTcg9MTZx-Pm3FVpzey5hDMzEoopJVfmEqgkEulkb17YVBA",
      "https://play-lh.googleusercontent.com/6fpKmEoGVTbKChWNy5d8hZkEL5yhENRHrzPuOC26YDlvymbjkhEYeMTrqWXeg009JLM",
      "https://play-lh.googleusercontent.com/vz3Dk6q9vkPdxSrDIn8XhLcc8ezYxWc6csTmpr5cN_yr03AzqnU0Yurq97hiTBA2Rrw",
      "https://play-lh.googleusercontent.com/eaKiEK-U05mAJTaDALiIthv0Yyexr3bOjZcNB7Jlq31fg8qQlzUTjTLRJH5kTUAfGwa6",
      "https://play-lh.googleusercontent.com/-cfCi-9UZsN9VUrUnXjICX3JsQQ-yYtHu-KZmGupvwddHaNbiyICVtxwjYEg6tl78DA",
      "https://play-lh.googleusercontent.com/NqcvqlVf1MO7QNEooW-o9G68jyangTLmoZI9y1jJZNTtaqNRcsEq1UOSOzCc9gHfBqfc",
      "https://play-lh.googleusercontent.com/daBQA2gdt5_jKq7gH5dqWqmw2YwIq_im8K9u3tJp5-HnGAnzyyjPBvCk_AEDFxE8_z-a",
      "https://play-lh.googleusercontent.com/9M6Ycm5mr9R_PlnJumcHzMvSN4vD6TWemlcQH90WLwssxtPEkVpjVR4sMdvJkM-xb6gy",
      "https://play-lh.googleusercontent.com/tfj7uczazD3_g1pCopb9_fPyXL1yAs83Xmhylxv03U_eczS0LePPGu4HHAFV_alCv48",
      "https://play-lh.googleusercontent.com/QMycIxS8JxTsCHUVCxzAVakVFAP-Tp0d4BQwHGP_E0o8q0QD_z2zbJ_1ySGyMGQGvA",
      "https://play-lh.googleusercontent.com/c7_tSsX0eoIeO6cw_X0s0d6RmIhUBU6_9V5SGlI4vB7Cc5cnMVeU7fAau9M5nc3_2cI",
      "https://play-lh.googleusercontent.com/m3t33hr_X3BGhmCEYLbDMfzIPR01z-WxVtFTdI9aR9W7g6TUfrHK7pOTpFhCdlepiJ4",
      "https://play-lh.googleusercontent.com/zGUGGf78eGoMd-zHuam3xc5DoyQv0ulSufFq3Noaqse61bIyrYptpV-ssL8MUiVq7To",
      "https://play-lh.googleusercontent.com/VQg_AygbXz8-t0916vaQUUT1i6Tbb1NoUU0Febz2nr7sA0zgXd0_lqyGtLZwqpGR6qE",
      "https://play-lh.googleusercontent.com/qopUDiv0Y5ONHQYfB3jblmaf4V0gJuJrdgLfFNGnhRtIA65cTAfqu6tlBXnOrjL1qikW",
      "https://play-lh.googleusercontent.com/ar6uxBHFO6Sl-TFIKOorPcIxKO-0AB6HGsKMDTU-yYRHUa84EufoHEtfjjPOEOUxng",
      "https://play-lh.googleusercontent.com/AFFpM-JZR1ZEd5klZ3ugx4cbaI8DeXMPXdR3HwZR-hmdj78-boNo4dmluDmDZv9-kA",
      "https://play-lh.googleusercontent.com/hVcU2PWJHdEKxp2bvHdhrTzJdfB50aULiT1IxNIITBaI-6clouMvtn2D31NL1MdeEbs",
      "https://play-lh.googleusercontent.com/bJFMOYFciSXsUjKXulz5D3woH5TgywkeiQ1YYDaYu9j3PhbMESRjkH6RCgNA7gGGeik",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/jm0217jbZ0VJhGU7ecHHoi7MOcY7KMvxY5t1bIsc3KSVwLNbTwkwsfvtHvQkfabSmyNH",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:Y9XPI0Ss3tM",
  },
  {
    app_id: "com.audible.application",
    app_name: "Audible: audiobooks & podcasts",
    app_category: "Books & Reference",
    app_developer: "Audible, Inc",
    num_downloads: "100,000,000+",
    app_description:
      "Get entertainment that moves with you this summer. Wherever your travels take you, indulge in a binge-worthy library of audiobooks, tune into exclusive podcasts and discover genre-bending Audible Originals. Listen to carplay on the road, plug into a podcast on the commute; enjoy bestsellers at your leisure and download and listen to content offline. The Audible library is endless, so listen to an extensive range of content and series and enjoy Audible as part of your daily listening routine.\n\nStart listening now - no membership required! Download and listen to Choice by Jodi Picoult. Also check out Beck Dear Life, part of our Words + Music series.\n\nTHE PLUS CATALOG\nListen all you want to thousands of select originals, audiobooks, and podcasts including exclusive shows and series. All Audible plans include unlimited access to streaming or downloading anything in the Plus Catalog.  With new titles added every week, there’s always something new to listen to for every mood and moment.\n\nUNPLUG BY TUNING IN \nListen to storytelling that enriches you. Check out the latest sci-fi fantasy books , unwind with meditation titles or tap into your detective skills with a new mystery series or true crime podcast. You can download, stream and listen to audio books offline too.\n\nHear captivating audio books, listen to podcasts and relax with mindful meditation. Make your Audible Library the listening routine you can’t live without.\n\nLISTEN TO AUDIO STORIES ANYTIME \nOur Library of audio entertainment is always open. Listen to bite-sized audio content like the latest fantasy series, true crime podcasts, romance books and sci-fi audiobooks. Whatever your mood - your listening routine starts here.\n\nDownload and listen to books, series, and podcasts offline. Dive into an engrossing true crime thriller, mysteries, sci-fi series & fantasy, kids stories, meditation titles, memoirs, documentaries, and genre-bending Audible Originals.\n\nWith monthly credits, you can find the audio content you want, including bestsellers and new releases. Discover a variety of books and audio entertainment with Audible.\n\nAUDIBLE PREMIUM PLUS\n- Build your own library and listen to the largest selection of audio titles from the entire Premium selection - titles purchased with credits are yours to keep, even if you cancel.\n- Sci-fi fantasy books, mystery & thriller, true crime stories, comedy podcasts, romance novels, meditation and more - you get 1 monthly credit to pick any title that you want to keep.\n- And, access the entire Audible Plus catalog - thousands of binge-worthy audiobooks, exclusive podcasts and audio entertainment, with fresh audio content added every single week.\n- Plus, you can listen offline to any title. You can download, stream or listen to books and other audio entertainment titles from the Audible Plus Catalog.\n\nListen how you want. And never lose your place with seamless cross-device listening with Whispersync, available with all audio book titles, podcasts, series and selections across your library.\n\nSELECTED AUDIO STORIES, SERIES AND TITLES\n- Explore the Audible Plus Catalog anytime you want, no credits necessary.\n- Thousands of binge-worthy audio books, podcasts and Audible Originals.\n- Fantasy series, mysteries, sci-fi audiobooks, kids books and thriller. Listen to books and podcasts from thousands of titles.\n- Fresh audio content and new listens added to the Catalog every single week. \n- Listen offline. You can stream and download all you want.\n\nThe most compelling stories & podcasts. Told by inspiring voices. Listen to storytelling that speaks to you, anytime, anywhere. Fall in love with books all over again with Audible, an Amazon company.",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.audible.application",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 4,
    photos: [
      "https://play-lh.googleusercontent.com/MYIzWDpU_h5srVy1GUewBMMhoj-ZadN_z44Jyjp7HdYYB3cer6kWHzCvUh6T_W32XXc",
      "https://play-lh.googleusercontent.com/BiI2gZMPFArJlrvGf8H2rKRn_GMxxRISZ6xz4ZQ57NLzWZHSuQcwVkAzuwHZmClOjw",
      "https://play-lh.googleusercontent.com/mpfVVr3Ik1xlcrJXblujxc1LhDb87HOkFhgRt6mKs5GYo9ngHmx4C6b7p7C75XtpOG8",
      "https://play-lh.googleusercontent.com/LaqQF2KHc4zNOooHE3fEgOey9YjwkM80Wx6TEXSzGCujCakCVzcXB25bcooT1U_7Yg",
      "https://play-lh.googleusercontent.com/2yl0gIDB8mViyOLil0bFt7QvScTfcA3QCuQtJjUB4iZyPoJqXzkwdav06Vx-mRBCmvw",
      "https://play-lh.googleusercontent.com/LYT15tqjGgzan-T64ctQognEIw9eCGJwM3kW6xy2Idh9oe1Jy4Dp8C_nbvAcLkcm8A",
      "https://play-lh.googleusercontent.com/sQO1u4CJfHLVMLfLIISLnIIhgKz2UkAKyiF8xnQkZTSyEzlsobXK_oGijEQztOZZi2Y",
      "https://play-lh.googleusercontent.com/QdXEhsbVAauy0KRlQuOfhllG1a6XWl466yXGIdl1J_f0xexurV-K8ZLGU08Z-UhL2t4",
      "https://play-lh.googleusercontent.com/pZBTpr9FlGavNyA4p9WnsbN_6yrFgr8MbD3LIRQ_HItvHYPC8_eV-jbqSi1utKcDPUw",
      "https://play-lh.googleusercontent.com/21-2xogjxMwMCl8CymCpQZJ83QcxgfSEM0ivpuyc_dv4FL6MYGcXYZU3QKE-xLl_IjI",
      "https://play-lh.googleusercontent.com/jKYSxIZ2eUoXCr2FnL80R-3uJkkrRPAKD6eZBFyWDzQhmM8HPOI8v8-cfllEMaV6AQ",
      "https://play-lh.googleusercontent.com/kwKGlxXqB1VeK9L7buuq2vmjJZR1ByVGsllu-P7_UhgV7oPbDHWyuAhr5gcH7h3P5ks",
      "https://play-lh.googleusercontent.com/PPABEvRRnB1N3rBeYQGXb2JmckGstAMR2Sd_rdEjjQRFnrFYmCVqevYDaLWDRpfpMqw",
      "https://play-lh.googleusercontent.com/CBRl3FFXbDt00v6vO982obFPZbjm-dBqaHpP1nyBnkMqss16PdMi2Kikqe0xsSUbxkg",
      "https://play-lh.googleusercontent.com/miVzUl2rpGX3xH6ihlHlbSXiJEO--246lDMQMWta6o6wHKKtkAgSGmjtpNuddJtzF1E",
      "https://play-lh.googleusercontent.com/PliJY8BDgUtPqTyTHsH1hqTsjQ1_vqYzvWE79vZm2ulubTMiYoq_Cjfe_7l7a-x_HlqZ",
      "https://play-lh.googleusercontent.com/4vSTRZEhb18gz9ibClzGPlbrqQw2IXYE0EAFKeKj4mYj_kw0J-KrM76odLyjomvoTA",
      "https://play-lh.googleusercontent.com/Lc49DkK9x5L-rWf9x7rm5JDFkFCgKHQ3OpW3-zL_fmiw5WVSm7s9zdEFCSljJZiHSRNo",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/pwzZK-7oQexraeU0mOrQgFIck-QSS89rH0eWjehctp8XskRSpixPNVlA0YYlRXHbA2Iz",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:h6oNH-uGXxE",
  },
  {
    app_id: "tv.twitch.android.app",
    app_name: "Twitch: Live Game Streaming",
    app_category: "Entertainment",
    app_developer: "Twitch Interactive, Inc.",
    num_downloads: "100,000,000+",
    app_description:
      "Watch livestream gaming videos, Esports and any IRL broadcast on your Android device! Stream your favorite MMO RPG, strategy and FPS games for PS4, PS5, PC, Xbox One and Nintendo Switch. Twitch gives you live streaming and gamer chat in the palm of your hand.\n\nSports are here. Tune into your favorites: basketball, baseball, soccer, football, swimming, wrestling, hockey, pool, and much more through talk shows, league channels, Fantasy, and ESports.\n\nLive chat as you watch gamers play everything from Valorant to League of Legends. Watch Fortnite Battle Royale, Minecraft Sessions, 2k Blacktop, Overwatch killstreaks, and FIFA showdowns. Multiplayer games not your thing? Livestream any IRL content you can think of, from art demos to animal videos!\n\nTwitch Game Live Streaming and Chat: TOP 3 FEATURES\n1. Watch gamers play any single or multiplayer game; with Minecraft, Fortnite, CS:GO, PUBG, FIFA, League of Legends, Call of Duty, Valorant, Grand Theft Auto, Overwatch, World of Warcraft: The Burning Crusade, Apex, WildRift, Garena Free Fire and much more. You can really let your gaming flag fly! Stream content from the biggest MMO RPG, MOBA, strategy and FPS games out there, or settle in for nail-biting Esports tournaments.\n2. Live chat during any gaming, Esports and IRL broadcast. Connect with your favorite streamers and fellow gamers to talk strategy and gameplan.\n3. Broadcast your very own gaming content! Livestream GTA on Xbox One, build Minecraft monoliths on Nintendo Switch, take down your Fortnite enemies on PS5, dive into WildRift on your mobile device, or show off in Valorant on PC!\n\nLooking for something other than gaming? Join live discussions around your favorite sports, listen to podcasts, check out music concerts, or just chat within the community. \n\n+ Stream interactive live news videos with exclusive content for PS4, PS5, Xbox One, Nintendo Switch and PC.\n+ Watch unique programming: livestream anything from art demos, to music festivals, to just chatting with others!\n+ Discover new multiplayer games and IRL videos with ease thanks to simple and intuitive navigation.\n+ Switch to Dark Mode for those late night viewing and gamer chat sessions.\n\nJoin the millions of hardcore and casual gamers who have found a place to connect over the MOBA or FPS games they love. Take your passion to the next level with Twitch!\n\n------\n\nFor feedback and assistance, please visit our Support Center: https://help.twitch.tv\n\nPlease note: This app features Nielsen’s proprietary measurement software which contributes to market research, like Nielsen’s TV Ratings. Please see http://priv-policy.imrworldwide.com/priv/mobile/us/en/optout.html for more information",
    app_page_link:
      "https://play.google.com/store/apps/details?id=tv.twitch.android.app",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 4,
    photos: [
      "https://play-lh.googleusercontent.com/-LR1bpT8qoXESZ-BSHo33A4CODrU97LtXUxUNrHGKUr7Ss9qHCzV45qcBao_f-bU6F7m",
      "https://play-lh.googleusercontent.com/gCIxulUYsIf55NeR9j7ydn-UFXe6pFdnoMXx14vRlu4J2xDT9W0OPBsxOo-wpgQsohY",
      "https://play-lh.googleusercontent.com/VsxLK5Z2xZAmSZSSHI79vWOt-R-PDYgGVZxafPljVRZjFjrfB-lGdnnSZR0PziTDN_UO",
      "https://play-lh.googleusercontent.com/tFhX7nr-3rlE3bGUeRVtrLzGk1wpAD85v3_KRKWk3E7bW-DHuvJK6RrX9Wh5girKpA",
      "https://play-lh.googleusercontent.com/FOY5YFMYQUdD93TC7QDDlcBk0oUjs_DMrsBmcFJHOJXq8vJ7M7yj9yVCkzF9aPyanGg",
      "https://play-lh.googleusercontent.com/Na5JFTWuVRLejOty92trFndWhaiMovvnaT01Eb73sBd3n4dwcWscGF5sFbjuq8DrDDk",
      "https://play-lh.googleusercontent.com/hYkjpmmaPwEPHWmov3XzHiCAbXVV9Wg_BpgAJF6yH6aomzBI0wUkd4jiYSoj7u4XDgM",
      "https://play-lh.googleusercontent.com/CHHwJz5IncMq8VD1S6EGRWLFC933Oxw6Cr8Rd8uOoOhQ46pEI7PAwf2IXFQbk8IvRA",
      "https://play-lh.googleusercontent.com/j7rmYlNidq7weLDZX7t34qhBnarubsHautyu8-kvS7l6Hgx0J058l3V-VCcn1Oz83Uk",
      "https://play-lh.googleusercontent.com/hr-H3SlDquZRAFIarw1VzqXIm5R57WPI6LYVY7gmkuI-OAzokK_ZIUmoy_zSz51ufxV_",
      "https://play-lh.googleusercontent.com/CQQVB484xWZksKrT4HDSNP_Q2VT1gmd5U2I3g0wYYQI2MHkqsnYaHnasrPO3OyATreE",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/QLQzL-MXtxKEDlbhrQCDw-REiDsA9glUH4m16syfar_KVLRXlzOhN7tmAceiPerv4Jg",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:ROfOBZYBwI4",
  },
  {
    app_id: "com.bumble.app",
    app_name: "Bumble - Dating. Friends. Bizz",
    app_category: "Dating",
    app_developer: "Bumble Holding Limited",
    num_downloads: "10,000,000+",
    app_description:
      "Millions of people have signed up to Bumble to find dates, make new friends, and meet new people.\n\nBumble is a free dating app and social network for singles where you can find friends and meet new people. Whether you want to meet friends, make genuine matches and meaningful connections, chat with strangers and new friends or look to expand your professional and social network. \n\nChanging the rules of dating\n\nBumble is a free dating app founded on respect, equality, and inclusion. You can find dates, make friends, and meet new people the way you've always done — but on Bumble, women always make the first move.\n\n- With Heterosexual matches, women have 24h to start a chat, and men have 24h to respond\n- Other matches have 24h to start a chat or reply before the match expires\n- Bumble comes in 3 modes to suit what you're looking for: Date, BFF, and Bizz\n\nDiscover our amazing free features\n\nMeet new people, make a video call and find a great date or chat with your new best friend using our free dating app:\n- Unlimited Swipe: Meet new people by swiping left and right as much as you like.\n- Unlimited chat so you can find the right matches.\n- Link your Spotify and Instagram account to share your interests with potential dates and friends\n- Use Video Chat to get to know your matches better\n\nMatch with the right people\n\nWe're the first app to combine dating for singles, meeting new people, and making professional connections all in one app. We make it easy for you to connect.\n- Use Video Chat to get to know your matches better\n- Send your videos and favorite pictures while you are chatting with new friends\n- With Snooze Mode, hide your profile whenever you want (you'll still keep all your matches!)\n- Link your Spotify and Instagram account to share your interests with potential dates and friends\n\nBoost your dating life with bumble premium\nBumble is a free dating app and always will be! Our premium features help you enhance your Bumble experience.\n- See everyone who swiped you right (your Beeline)\n- Rematch with expired connections for a second chance at a date\n- Extend your matches by 24 hours\nThe buzz is real\nBumble is much more than just a dating app for singles. Join our genuinely inclusive dating community, meet new people, make friends or find your ideal partner or date.\n\nHere are our core values:\n- We believe healthy relationships are fundamental to living a productive and positive life.\n- In the fight against old-fashioned hetero-norms, women always take the first step.\n- We've changed the rules of the game to switch up the dynamics of dating.\n---\nBumble is free to download and use. We also offer optional subscription packages (Bumble Boost and Bumble Premium) and non-subscription, single, and multi-use paid features (Bumble Spotlight and Bumble SuperSwipe).\n\nhttps://bumble.com/en/privacy\nhttps://bumble.com/en/terms",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.bumble.app",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 3,
    photos: [
      "https://play-lh.googleusercontent.com/G8bvqcWFcO-umC05l-Wab8nmulU3YvoXpXcv3LWR3L8bAaGJMJjcSAL8ibIyk_EwJtA",
      "https://play-lh.googleusercontent.com/3LQArD8QgK6nAEyeBGISG0_2CFuCryMaQuNTmEqFuMPf-yUFbwoVsL3eRk6yy-R60SE",
      "https://play-lh.googleusercontent.com/YFVAhYZydkYUt_sFYyyz9m705l-M4CnPf2RNLxaxlBgyads259RTNkN4hP-3lI65__Is",
      "https://play-lh.googleusercontent.com/GidtZiPtyVZZnxaVQJjcFl_4l1iRTRBLy-l921QHY4YObYD8vQyUhca8LT8hwZ4rVDdQ",
      "https://play-lh.googleusercontent.com/cU1VPXB4w0h6yDtGAIigCTFdB-IY_RqSh49XbkadIb8lUt2gPVNXp7TZq4pGLM1AStU",
      "https://play-lh.googleusercontent.com/Fd-w157S1AIb6G2_u3g-h2wmBUnVgIEGNsHPd1mts0xfMX1RrxLJlicea3c4kxlSpCzZ",
      "https://play-lh.googleusercontent.com/D2Ypn7hRbgKAZv3rZ0nc8ET7ZUTteh5M8u1MwU35439f3vf1jTpkDgsj1TLespvYIg",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/tH2ui3MqYnTyt7EG9S3DVNDO7SV7eRtts2phjaE-vZNBvf4meAx5_a5LZc_IbZGAFw",
    trailer: null,
  },
  {
    app_id: "com.peacocktv.peacockandroid",
    app_name: "Peacock TV: Stream TV & Movies",
    app_category: "Entertainment",
    app_developer: "Peacock TV LLC",
    num_downloads: "10,000,000+",
    app_description:
      "Download Peacock, the streaming service from NBCUniversal. Peacock has all your favorites, all in one place. \n\nWith Peacock, stream new movies and thousands of TV show episodes — including Parks & Rec, Yellowstone, Modern Family, and every episode of The Office — plus exclusive Originals and current series from Bravo and NBC. \n\nStay up to date on live news and stream all your favorite live sports including WWE, NFL, MLB, Premier League, golf, and more. \n\nHere’s what you get with PEACOCK: \n•\tInstant access to hundreds of movies from major Hollywood studios such as Universal, DreamWorks Animation, and Focus Features. \n•\tThousands of hours of TV series, including full seasons of buzzworthy faves, bingeworthy classics, and current-season NBC hits. \n•\tPeacock Channels – playing your favorite entertainment, 24-7. Scroll less and watch more with the SNL Vault, Fallon Tonight, NBC Sports on Peacock, WWE, NBC News NOW, TODAY All Day, True Crime, and Dateline 24/7. \n•\tA daily dose of live news with the best of NBC News, CNBC, MSNBC, and E! News – plus Late Night, SNL and more. \n•\tHit Spanish-language TV shows and news from Telemundo. \n•\tUp to 6 personal profiles to optimize your viewing experience. \n\nUpgrade to PEACOCK PREMIUM ($4.99/month) for an all-access pass to everything Peacock has to offer – watch every movie, episode, and season, plus stream your favorite live sports and events. More to watch. More to love.\n \n•\tStream everything— including new movies, full seasons of exclusive premium TV like Yellowstone, and your NBCUniversal faves from Bravo, SYFY, USA, E!, and Oxygen. \n•\tEvery WWE Premium Live Event —including WrestleMania—plus series, docs, and the WWE Vault. \n•\tExclusive Peacock Originals, including Bel-Air, Below Deck Down Under, The Resort, Girls5eva, Dr. Death, Vampire Academy, Love Island, The Real Housewives Ultimate Girls Trip, and more. \n•\tMore live sports, including exclusive Premier League soccer matches, football, golf, MLB Sunday Leadoff, and IndyCar. \n•\tThe streaming home for your Bravo faves, including The Real Housewives of Beverly Hills, Top Chef, and more. \n•\tCurrent-season NBC hits like the One Chicago franchise, The Voice, Law & Order: SVU, Young Rock, and Grand Crew. \n•\tUnlimited access to the entire library of Kids and Family entertainment.\n\nWith PEACOCK PREMIUM PLUS ($9.99/month), get everything included in Peacock Premium as well as: \n•\tStream Peacock ad-free*. \n•\tDownload available titles to your mobile device and watch later, anywhere.\n*Due to streaming rights, Peacock Channels, events, and a few shows & movies will still contain ads. \n\nContent availability may vary over time.\n\nPlease note: Use of the PeacockTV app is limited to the United States and its territories. Video is accessible via 3G, 4G, 5G, LTE and Wi-Fi networks. Data charges may apply. \n\nIf applicable, subscription charges begin after any promotional period of Peacock Premium/Peacock Premium Plus concludes. You will be charged on a recurring basis as described above, minus applied offers plus applicable taxes. Your subscription will auto-renew until you cancel. Cancel at any time by visiting your account in the Peacock App. By subscribing, you agree to the preceding subscription terms and our Terms of Use and Privacy Policy below. \nUpgrade at www.peacocktv.com\nTerms of Use: www.peacocktv.com/terms\nPrivacy Policy: www.peacocktv.com/privacy\nCustomer Help: www.peacocktv.com/help\nDo Not Sell My Personal Information: www.peacocktv.com/do-not-sell-my-info \nCA Notice: https://www.peacocktv.com/ca-notice \n\nThis app features Nielsen proprietary measurement software, which will allow you to contribute to market research, like Nielsen’s TV Ratings. To learn more about our digital measurement products and your choices in regard to them, please visit http://www.nielsen.com/digitalprivacy for more information.",
    app_page_link:
      "https://play.google.com/store/apps/details?id=com.peacocktv.peacockandroid",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 3,
    photos: [
      "https://play-lh.googleusercontent.com/o6qT-CsMHqM6k0jlwacK43s8-eW_xMJYFOknHbu06Joi8H15-LALJcWBxXuU2HoQHEpN",
      "https://play-lh.googleusercontent.com/a7JQA6DpIKy_cLvV9P5ssXa6BNn66fXuUNBVrU_xJIwXQ24c2r16GMtd-VmTD3WwUu4",
      "https://play-lh.googleusercontent.com/CKSOhYYPxSnvOvMP_8ZkKnehK4Eq1_gi-JMouguWGFgOhdAmvkoeleQnrDVi4iQhAw",
      "https://play-lh.googleusercontent.com/tKIgjtE9CBu47GFyfMDEWx6YPRds11R1OabVZhoGzuaSBeHM5tKwFiHvvt0_SspBirk",
      "https://play-lh.googleusercontent.com/DhN73Guz3nJGML_vzFqv-d1JY3Tf93XBFn6EoZ08dkCKxp-q7k2HU7y6_nSFBoYrVB0",
      "https://play-lh.googleusercontent.com/AMSamegG6NfQB2Q3isNJXv3gPck00QzV8GuIA2vhLClCabAD2Zloz0gOCPLaczN0Cw",
      "https://play-lh.googleusercontent.com/OVN9UsFnEAw6-QJN5U5RmfNkh_fNZY1yoivA7U-hPkPjKhnXSzgDfwLZs-4OgWK6xzQ",
      "https://play-lh.googleusercontent.com/2tA_TsX3vjBuKu1sW5OT_gEGpgF8j9IeL936kRq0ak47ym_ckBw9ySNmBXJN1dBM5Q",
      "https://play-lh.googleusercontent.com/j1A-2hUz-delFOQmrIclYkLkXsRBK7DroEDwNqMnmdk2BnL0ZVXyZYCZqO0KAm46Irc",
      "https://play-lh.googleusercontent.com/2zxsB0lDerpn28gTpvBtNg39Fufh3YvioRQqG5QdWga_8ZRY9nBC__Oy2-okvNJVwWRR",
      "https://play-lh.googleusercontent.com/rOeSVNVhZhZZ66b68VP9X7FkDozLdMp--oX91pF2AvIkH_D0zNIKV1AZ2k-QCOAv6Q",
      "https://play-lh.googleusercontent.com/0klIStBE_P34E1YQq4HFS5Vc1hQ6wSEb6KNh8MdC8OaNW1fgoHTPSCI5mzcxAgTzQfOk",
      "https://play-lh.googleusercontent.com/0TrgpVJkaWqT5qHUf_9GayW7-ICpq8G4EIEudTjx324Y78dc3Z3iwHCNFFccp7C-LzOZ",
      "https://play-lh.googleusercontent.com/TDlVVeQhMOe_DB-sdRAB7tQ4ZE8yQ-NftccE3zkRdW66frpHXdksjoKXOhzH-YCCCZw",
      "https://play-lh.googleusercontent.com/87eEjEKSd7cZoYC0JmWfbI-26moNzoyKajeX6d6nbUVdemuGg1NzgXIiSmK_9tmU4SM",
      "https://play-lh.googleusercontent.com/frPReN9-kMDVzSde1qy4FAq06Hi1EcaNzjGqHikZQbU_Ze36lBVGA-tXrrF928Lye7E",
      "https://play-lh.googleusercontent.com/K8jUHU-ESfi-i4tMzt_4-s2BRQwcv5vSCTM1Jbex9LLIkG6IEszMvJYejV_-LDEfcIM",
      "https://play-lh.googleusercontent.com/oazmer3XxT2XdjamfhGVrnuoMTTxtm_UwTfuqyEg3BYTpHPF9RzC0jCWq1JKy8EvhhSL",
      "https://play-lh.googleusercontent.com/f41QrRvua6rrSSesPRW9tbLIrMA9x3XCABQpxcNYL3pFowIjs-yr1euW9kHOhbp492PS",
      "https://play-lh.googleusercontent.com/0gCtRVPUc5gC3g_kfKNI5eIHWmtEPV_S1yglnXUJsB-PLiYk52UV39Y8NIFPFWjeig",
      "https://play-lh.googleusercontent.com/ifauaGWxbBOrpf62KzCTF3erD9LHODb6Qr52GtFWFgGFHjQeeTAnsBRN_Av5l7q-EeM",
      "https://play-lh.googleusercontent.com/klw_o_BfPjcTwL91RT2XTtrVtGBvcodJWhopAdqJ0U3t4060QqCRPOSqyEfzUIZ-nw",
      "https://play-lh.googleusercontent.com/X3fssWkdjI60foW-G19Snneo8Cij6T7UtCBA0dxvej3crF1GFzC88AeTSJ3jsudMspk",
      "https://play-lh.googleusercontent.com/LX-2TlSRwNrouBArBaRcr6ndLGG9GIlMQDojBhGkwpmSYXEo3OhicbyuU47gVRGENAk",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/IdHOrlnq_yC9w5NGHollnGnunojuEW1_-8g32VaETN3kkXkTOTi001XN2TBykRC3Tg",
    trailer:
      "https://play.google.com/video/lava/web/player/yt:movie:_h_qjXSLHQI",
  },
  {
    app_id: "com.cbs.app",
    app_name: "Paramount+ | Peak Streaming",
    app_category: "Entertainment",
    app_developer: "CBS Interactive, Inc.",
    num_downloads: "10,000,000+",
    app_description:
      "Welcome to A Mountain of Entertainment. Stream tens of thousands of full episodes—including favorites from CBS, Nickelodeon, Nick Jr., Comedy Central, BET, MTV and Smithsonian Channel—plus exclusive shows, brand-new originals, and live sporting events like UEFA Champions League and the NFL on CBS, when you subscribe to Paramount+.\n\n• Watch full episodes on demand from hit series like Survivor, NCIS, SpongeBob SquarePants, Ink Master and more! (Plus, it’s all ad-free with the Premium plan.*)\n• Obsess over originals. Watch subscriber-only originals such as Halo, Star Trek: Picard, 1883, iCarly, SEAL Team, and The Good Fight.\n• Make every night a movie night with blockbuster hits and fan-favorite films from Paramount Pictures, MGM and more.\n• Access 24/7 live streams with around-the-clock news coverage on CBS News, scores + highlights on CBS Sports HQ and entertainment news on ET Live, plus 20 live channels of curated favorites.\n• Create up to 6 individual profiles for each member of your household. Have kids? Use our Kids Mode profile feature. \nWatch live sports like NFL on CBS & UEFA Champions League.\n• Save your faves with our watchlist feature, My List. \nStream your local, live CBS station (Premium plan only).\n• Catch the best in live events including NCAA March Madness, The Masters Tournament, The GRAMMYs and more (Premium plan only).\n• Download and watch offline* (Premium plan only).\n• Stream even MORE originals, movies & sports when you get the Paramount+ with SHOWTIME bundle.\n\nTry Paramount+ FREE now. After your trial, it’s only $4.99/month or $49.99/year for the Essential plan, or $9.99/month or $99.99/year for the ad-free Premium plan.* \n\nDownload the app now to get started.\n\n*Live TV includes commercials and select shows have promotional interruptions. Downloaded content is accessible for earlier of 30 days from date of download or 48 hours from start of playback. Content availability subject to change. Please note use of the Paramount+ app is limited to United States. Paramount+ promotional offers for new subscribers only. Live TV subject to availability. Prices shown are in U.S. dollars. Other restrictions apply.\n\nYour subscription will automatically renew after any applicable promotional period and your Google Play account will be charged the subscription price on a recurring basis until you cancel.  You can cancel your subscription at any time through your Google Play account settings.  If you cancel your subscription, the cancellation will go into effect at the end of your current subscription period, as applicable. You will have continued access to the Paramount+ Service for the remainder of your paid subscription period.\n\nPlease note: This app features Nielsen’s proprietary measurement software which will allow you to contribute to market research, like Nielsen’s TV Ratings. Please visit http://www.nielsen.com/digitalprivacy for more information.\n\nParamount+ Subscription Terms:\nwww.pplus.legal/subscription\n\nViacomCBS Privacy Policy:\nhttps://www.viacomcbsprivacy.com/policy\n\nCookie Policy:\nhttps://www.viacomcbsprivacy.com/cookies\n\nDo Not Sell My Personal Information:\nhttps://www.viacomcbsprivacy.com/donotsell",
    app_page_link: "https://play.google.com/store/apps/details?id=com.cbs.app",
    price: 0,
    price_currency: null,
    is_paid: false,
    rating: 3,
    photos: [
      "https://play-lh.googleusercontent.com/uj2vzenBguyYEbIp88KSW1HRXtPbbbzyk_cU0W_PBo-USatMrpqCpOqfvh8ZbGPuk9M",
      "https://play-lh.googleusercontent.com/jt1t7og5vH24JPPAnQhMi_Y1cHsMuH5BzsqDggMkMyNltGVxALCTAXBorXgSIvNyZSw",
      "https://play-lh.googleusercontent.com/UtgnKDqP7VQBvqB7OByLjzhgFnAsSsaFSw7lsq41vNyJB83XfHd1UpiPsEVUpadNnEMn",
      "https://play-lh.googleusercontent.com/kDJMERPcNFaTsXYChq2F2on_FMwJ7xWdKOoaGLwrzrK9HxAl6ksUSQPN73raw9wSKfU",
      "https://play-lh.googleusercontent.com/b6A-ehg6VyHn3105L2jwxHU5m8fvRYGMF0NiA7SVx-67P8PC5633zg9VLWc15I1hwdC4",
      "https://play-lh.googleusercontent.com/mHE1LqLdyM6P9oerK58Xy5yhzch6zNkWo4AIh5SppahSg0f5ORQP0Q410nsduzrVDzg",
      "https://play-lh.googleusercontent.com/ytxj3hRZ7J-Wjf_FRT0IzjUi5NhTbPnQVGxqzR6dO5Uk9FrsFD4rqDc_LIsrqpPe8dg",
      "https://play-lh.googleusercontent.com/2375k2olclBnEYc8oU6L3RIbccHKtvKgwqG-bDUWxceBA50EcYIQDyg-XgBynBjiiaY",
      "https://play-lh.googleusercontent.com/sOoiHKNmhIGYu4tTQDODfRhq1MtRJ1toohhIrHqnojS1rhgdNUaoJ69ze9M1T8OpeSg",
      "https://play-lh.googleusercontent.com/X_McVYqjPv2ZM9exNR-54udxOCHJs8ZX4r1VdR9WYyotbVHYtfYODY0TyJb728_e4A",
      "https://play-lh.googleusercontent.com/wFiMp8DxOuIyedZUBWF8hMPnwkc_m4M0qRTVmZiM5n9LcrM5g3NcHbPNIxR4HOwejezk",
      "https://play-lh.googleusercontent.com/5S97GgycQOegpoOeGgFWQdm_uvyE4WmRdguxuM7JDiGMeyQygrAzsJZYuQfkW5keCUg",
      "https://play-lh.googleusercontent.com/HRR6r25IVQwMZ9UqpqHxlj8wgkl5db1LUBgCg95drvsOse6rOw76zi24wSZHrIHpuwc",
      "https://play-lh.googleusercontent.com/M-t8CoSisavROxESKUBYrMUDNdOui3tC-1oYJEDi0e_q697XNnYWAhQjwut54cE4bso",
      "https://play-lh.googleusercontent.com/wh8sjmku4FGUbwArsaITjZ3Nk5Qq4hgfwcbc-OxKPKptxy8PdXRE1lW2ix0J9HIlzxY",
      "https://play-lh.googleusercontent.com/mB61l_ILADXFDmboQlTpvjBdaIJGl1Kaah6V9_nOD_5t5sBYu-P6jeJAJ8hntZOxYq48",
      "https://play-lh.googleusercontent.com/x2uGmMPiBN_SC7jw3aO6yyBNuPLPDWL5h8Z_mr9d2_Unr8WPq7W9oHcFFZh1U1g2grk",
      "https://play-lh.googleusercontent.com/pRy4wgGVLv8-btzxnn-rkRYR4WjR1Jq6AV5JsSUjcOwjJ0ZLM5ytWFfvwPD_0r8DSG8",
      "https://play-lh.googleusercontent.com/cya-2ciEmNzbvKWrCFM7UWw3ysVZvHhmp3KfdcvrFmXxCfbjebZ6SuqiAaQ6JqaJnw",
      "https://play-lh.googleusercontent.com/RrNWykwhVslytSXfeSRx1pumOcV1RI7WbKFwfcRpsfiNKdiIIr0U6E1z4UD8v9zxcjM",
      "https://play-lh.googleusercontent.com/rLAxtUliKwvF2oTOTiv6LgGBlVr2WhLB3ingQfoHqoGJq06YQ6M_5gTpTi2783fv-9qP",
      "https://play-lh.googleusercontent.com/_BEQeLSdiWruqIbhUMkArg2KrwIOvXJa7jgIg50kMODAdrIG-jkpX94fXnawaHJ55vU",
      "https://play-lh.googleusercontent.com/82cPdCPIc3kfDkiKhDTGaMo5zha3h-CcdJZ9Ifx-yuJok5xONF64c2YyCp5k4HZU8kE",
      "https://play-lh.googleusercontent.com/GT4p6MbsQFH9LtW0VQlPVjFmiSRMZmxXnYDD7CB2FvTvxpQhAFkctcHnpkuHwSCTXuk",
    ],
    app_icon:
      "https://play-lh.googleusercontent.com/oi4GE8ulxHp4Y2xVzKu_WAMrgE4Jj4Kbdd7hAWLeoZTsMtC5bYTd2xcYhlvMk69pTFY",
    trailer: null,
  },
];

// iOS
export const iOSTopApp = [
  {
    app_id: "835599320",
    appId: "com.zhiliaoapp.musically",
    app_name: "TikTok",
    app_category: "Social",
    developer: "TikTok Ltd.",
    developerId: "1322881000?uo=2",
    num_downloads: "10,000,000+",
    rating: 3,
    app_icon:
      "https://is3-ssl.mzstatic.com/image/thumb/Purple122/v4/31/bd/80/31bd8092-8f06-1a20-36f8-dccde55366c2/AppIcon_TikTok-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "971265422",
    appId: "com.hbo.hbonow",
    app_name: "HBO Max: Stream TV & Movies",
    app_category: "Entertainment",
    developer: "WarnerMedia",
    developerId: "1514826633?uo=2",
    num_downloads: "10,000,000+",
    rating: 4,
    app_icon:
      "https://is4-ssl.mzstatic.com/image/thumb/Purple112/v4/ef/1b/2c/ef1b2c6e-d54b-f385-5ddf-ca32f85ce972/AppIcon-Release-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "1446075923",
    appId: "com.disney.disneyplus",
    app_name: "Disney+",
    app_category: "Entertainment",
    developer: "Disney",
    developerId: "284888248?uo=2",
    num_downloads: "10,000,000+",
    rating: 2,
    app_icon:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/6e/a1/0c/6ea10cfb-2591-187b-a50f-4ce6ff7504bb/AppIcon-1x_U007emarketing-0-7-0-0-85-220.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "376510438",
    appId: "com.hulu.plus",
    app_name: "Hulu: Stream shows & movies",
    app_category: "Entertainment",
    developer: "Hulu, LLC",
    developerId: "376510441?uo=2",
    num_downloads: "10,000,000+",
    rating: 3,
    app_icon:
      "https://is3-ssl.mzstatic.com/image/thumb/Purple112/v4/bc/e6/75/bce67545-8674-38be-b2ef-cdc223a8712d/HuluAppIcon-1x_U007emarketing-0-7-0-85-220.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "530168168",
    appId: "com.cbsvideo.app",
    app_name: "Paramount+",
    app_category: "Entertainment",
    developer: "CBS Interactive",
    developerId: "295669712?uo=2",
    num_downloads: "10,000,000+",
    rating: 3,
    app_icon:
      "https://is5-ssl.mzstatic.com/image/thumb/Purple112/v4/ce/dd/ab/ceddab18-ac9f-c4df-4dcf-2f4c55fd8683/P_U002bAppIcon-0-1x_U007emarketing-0-7-0-85-220.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "1508186374",
    appId: "com.peacocktv.peacock",
    app_name: "Peacock TV: Stream TV & Movies",
    app_category: "Entertainment",
    developer: "Peacock TV LLC",
    developerId: "1508186373?uo=2",
    num_downloads: "10,000,000+",
    rating: 3,
    app_icon:
      "https://is5-ssl.mzstatic.com/image/thumb/Purple112/v4/e8/e5/96/e8e59657-9fc6-3eec-cea3-c6a394504c04/AppIcon-1x_U007emarketing-0-7-0-0-85-220.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "363590051",
    appId: "com.netflix.Netflix",
    app_name: "Netflix",
    app_category: "Entertainment",
    developer: "Netflix, Inc.",
    developerId: "363590054?uo=2",
    num_downloads: "10,000,000+",
    rating: 4,
    app_icon:
      "https://is5-ssl.mzstatic.com/image/thumb/Purple112/v4/aa/62/88/aa628896-1734-435b-4ef9-cc83d9ce4c0e/AppIcon-1x_U007emarketing-0-0-0-10-0-0-0-85-220-0.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "329913454",
    appId: "com.crunchyroll.iphone",
    app_name: "Crunchyroll",
    app_category: "Entertainment",
    developer: "Ellation, Inc.",
    developerId: "329913457?uo=2",
    num_downloads: "10,000,000+",
    rating: 3,
    app_icon:
      "https://is4-ssl.mzstatic.com/image/thumb/Purple122/v4/3e/57/ea/3e57ea51-ec84-3a56-b914-c7fd8f09676b/AppIcon-1x_U007emarketing-0-10-0-85-220.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "545519333",
    appId: "com.amazon.aiv.AIVApp",
    app_name: "Amazon Prime Video",
    app_category: "Entertainment",
    developer: "AMZN Mobile LLC",
    developerId: "297606954?uo=2",
    num_downloads: "10,000,000+",
    rating: 3,
    app_icon:
      "https://is4-ssl.mzstatic.com/image/thumb/Purple112/v4/f5/66/15/f5661540-f345-9333-f96c-cb18fb314d9c/AppIcon-1x_U007emarketing-0-7-0-0-85-220-0.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
  {
    app_id: "550221096",
    appId: "com.starz.starzplay",
    app_name: "STARZ",
    app_category: "Entertainment",
    developer: "Starz Entertainment, LLC",
    developerId: "550221102?uo=2",
    num_downloads: "10,000,000+",
    rating: 2,
    app_icon:
      "https://is4-ssl.mzstatic.com/image/thumb/Purple112/v4/48/eb/6c/48eb6c4b-b253-c3d3-ccd7-f551209eca7c/AppIcon-1x_U007emarketing-0-10-0-85-220.png/100x100bb.png",
    price: 0,
    currency: "USD",
  },
];
